[package]
name = "usedby"
version = "0.1.1"
edition = "2021"
description = "Small utility to see what us using a network port"
license = "MIT"
repository = "https://github.com/Herover/usedby"

[dependencies]
procfs = "0.16.0"
