[package]
name = "usedby"
version = "0.2.0"
edition = "2021"
description = "Small utility to see what is using a network port or local file"
license = "MIT"
repository = "https://github.com/Herover/usedby"

[dependencies]
clap = "4.5.0"
procfs = "0.16.0"
