name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source "$HOME/.cargo/env"
    - name: Build binary
      run: cargo build --release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/usedby"
    - name: Publish crate
      run: cargo publish --token ${{ secrets.CRATES_TOKEN }}